trigger:
- main  # Branche à suivre sur GitHub

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- script: |
    git remote add azure https://techempower@dev.azure.com/techempower/Activa_recrutement/_git/Activa_recrutement
    git push azure main
  displayName: 'Push changes to Azure DevOps'